_wandb:
    value:
        cli_version: 0.25.1
        e:
            d4vtvv8d7rang4w1qdxzv4nkj4jeuvuq:
                codePath: prototype/ppo_prototype.py
                codePathLocal: ppo_prototype.py
                cpu_count: 192
                cpu_count_logical: 192
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "15147421802496"
                        used: "9343333142528"
                email: beads0105@gmail.com
                executable: /home/yoonju/miniconda3/envs/NRL/bin/python
                git:
                    commit: a299e7811604a2113b93987cb7437b11de17bcda
                    remote: https://kim-yoonju:@github.com/kim-yoonju/SC.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-04d6ee81-3e90-1517-fed8-9ddca9218b6f
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-1fd03df7-4002-d22f-cf9b-096b6f4ec990
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-9d2f55ba-4ebd-786b-dc56-cc64be0db4f2
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-5bec7433-f720-614e-c090-866e987eb3e8
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-35cbfbd3-3db0-8308-73b4-32cf70e35f43
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-d68f2d2c-7048-d6dc-5c5d-940abccf14a6
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-1a4f6e5d-4e21-b61d-af7a-78f86a32757e
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-08a08dc3-40ed-5a8b-2613-0c78cf44db84
                host: Nova
                memory:
                    total: "811218984960"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: /mnt/yoonju/SC/prototype/ppo_prototype.py
                python: CPython 3.12.12
                root: /mnt/yoonju/SC/prototype
                startedAt: "2026-03-22T08:32:44.493897Z"
                writerId: d4vtvv8d7rang4w1qdxzv4nkj4jeuvuq
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 95
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 95
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.25.1
            "6": 4.57.6
            "12": 0.25.1
            "13": linux-x86_64
gamma:
    value: 0.95
kl_coef:
    value: 0.05
max_iterations:
    value: 1000
max_new_tokens:
    value: 512
max_seq_len:
    value: 4096
max_steps:
    value: 30
model:
    value: Qwen/Qwen2.5-7B-Instruct
ppo_clip_eps:
    value: 0.2
ppo_collect_size:
    value: 64
ppo_lr:
    value: 5e-06
ppo_max_grad_norm:
    value: 1
ppo_mini_batch_size:
    value: 4
problems_per_iter:
    value: 32
truncate_token_limit:
    value: 384
